# Pytorch 💻💻

PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.

<img src="https://full-stack-assets.s3.eu-west-3.amazonaws.com/M08-deep-learning/pytorch-logo.svg" />

## What you will learn in this course ? 🧐🧐

In order to train deep-learning models for computer-vision or Natural Language processing you will need to manipulate and prepare data for it. Therefore we'll learn to manipulate data using pytorch.

This lecture will work like a demo that you can follow along where we start with the basics of pytorch and learn how to load data and prepare it for training deep learning models. Here is the outline of the subjects we will cover here :

* General introduction to what is pytorch and why we use it?

* Understand how to use and navigate the documentation

* Intro to pytorch, tensor operations

* Data processing with pytorch, how to take different kinds of data and turn them into tensors?

## General Introduction

The main reasons why we chose to teach you deep learning through pytorch is its growing adoption in the fields of computer vision and natural language processing. Pytorch is also very flexible and customizable, so during the module we will go from learning how to use very simple functionnalities and digging deeper and deeper until you know how to reproduce any deep learning application using the library.

## pytorch documentation

The tensoflow documentation contains four main sections :

* <a href="https://pytorch.org/get-started/locally/">Installation guidelines</a>

* <a href="https://pytorch.org/tutorials/">Tutorials</a> with examples on how to use pytorch on practical usecases

* <a href="https://pytorch.org/tutorials/recipes/recipes_index.html">Guide</a>, a general walthrough the various functionnalities and additional libraries that come with pytorch

* <a href="https://pytorch.org/docs/stable/index.html">Pytorch documentation</a> a classic documentation describing all the different modules of pytorch.



Let's take an example page from the documentation so we can explain to you how to navigate, read it, and understand it :


## Practical introduction to pytorch on tensor operations

The main class of pytorch objects is... you guessed it : Tensors ! Tensors are easily convertible to and from lists and numpy array! This is great news because it means that anything you were able to do with numpy arrays will be possible with tensors as well, also tensors can easily be converted into arrays and the other way around.

Let's practice a little together :


In [22]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils.data as data
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Check PyTorch version
print(torch.__version__)

2.6.0


### Tensor operations

In [23]:
# Create tensors 
tensor = torch.tensor([[1, 2], [3, 4]])
print(tensor)

tensor([[1, 2],
        [3, 4]])


In [24]:
# Adding a scalar
print(tensor + 5)
# We summing elements with different shapes, something called broadcasting
# happens, that expands the smaller object so it can be added to the larger 
# object
# It's equivalent to this operation
print(tensor + torch.tensor([[5, 5], [5, 5]]))

tensor([[6, 7],
        [8, 9]])
tensor([[6, 7],
        [8, 9]])


In [25]:
# Adding tensors of the same shape
tensor2 = torch.tensor([[5, 6], [7, 8]])
print(tensor + tensor2)

tensor([[ 6,  8],
        [10, 12]])


In [26]:
# Adding tensors with broadcasting
tensor3 = torch.tensor([1, 2])
print(tensor + tensor3)
print(tensor + torch.tensor([[1, 2], [1, 2]]))


tensor([[2, 4],
        [4, 6]])
tensor([[2, 4],
        [4, 6]])


In [27]:
tensor4 = torch.tensor([[1], [2]])
print(tensor + tensor4)
print(tensor + torch.tensor([[1, 1], [2, 2]]))

tensor([[2, 3],
        [5, 6]])
tensor([[2, 3],
        [5, 6]])


In [28]:
# Multiplication by a scalar
print(tensor * 4)

tensor([[ 4,  8],
        [12, 16]])


In [29]:
# Pointwise multiplication by a tensor of same shape
print(tensor * tensor2)
# Element-wise multiplication with broadcasting
print(tensor * tensor3)
print(tensor * tensor4)

tensor([[ 5, 12],
        [21, 32]])
tensor([[1, 4],
        [3, 8]])
tensor([[1, 2],
        [6, 8]])


In [30]:
# Pointwise multiplication of tensors of different shapes
print(tensor * tensor3)
print(tensor * tensor4)

tensor([[1, 4],
        [3, 8]])
tensor([[1, 2],
        [6, 8]])


In [31]:
# Matrix multiplication
print(torch.matmul(tensor, tensor2))
print(torch.matmul(tensor, tensor4))

tensor([[19, 22],
        [43, 50]])
tensor([[ 5],
        [11]])


### Useful tensor attributes and methods
Here we present some common attributes and methods of tensors (we will discover many more in the future but these are really fundamental)

In [32]:
tensor.numpy() # converts the tensor to a numpy array

array([[1, 2],
       [3, 4]])

In [33]:
tensor.shape # gives the shape of the tensor

torch.Size([2, 2])

In [34]:
print(tensor.view(-1, 1))  # Equivalent to reshape

tensor([[1],
        [2],
        [3],
        [4]])


## Data processing with pytorch

In this part we will see an example of processing tabular data with pytorch

In [35]:
# Load dataset
iris = load_iris()
features, target = iris.data, iris.target


In [36]:
# To train deep learning models, we will use batch gradient descent
# Therefore we are going to form batch datasets with pytorch

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features,target)

# Convert dataset to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

# Create PyTorch Dataset and DataLoader
train_dataset = data.TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = data.TensorDataset(X_test_tensor, y_test_tensor)

# Shuffle and batch data
train_loader = data.DataLoader(train_dataset, batch_size=8, shuffle=True)
test_loader = data.DataLoader(test_dataset, batch_size=8, shuffle=True)

# Extract a sample batch
for x, y in train_loader:
    print('x:', x)
    print('y:', y)
    break

x: tensor([[6.3000, 2.5000, 4.9000, 1.5000],
        [6.8000, 3.0000, 5.5000, 2.1000],
        [7.7000, 2.6000, 6.9000, 2.3000],
        [5.6000, 2.9000, 3.6000, 1.3000],
        [6.6000, 2.9000, 4.6000, 1.3000],
        [4.9000, 3.1000, 1.5000, 0.1000],
        [5.2000, 4.1000, 1.5000, 0.1000],
        [5.3000, 3.7000, 1.5000, 0.2000]])
y: tensor([1, 2, 2, 1, 1, 0, 0, 0])


You now know a little bit about pytorch and how to process data now go have some practice on your own with the exercises!

## Ressources 📚📚

* <a href="https://www.tensorflow.org/tutorials/load_data/csv"> A tensorflow tutorial that goes a little further than what we have seen here </a>