# Numpy : manipulation de tableaux

In [1]:
import numpy as np

## Initialisation de tableaux

### Initialisation avec valeurs prédéfinies

In [8]:
# Déclaration d'une matrice de 0 (3*4)
print(np.zeros((3, 4)))
print()

# Déclaration d'une matrice de 1 (5*4)
print(np.ones((5,4)))
print()

# Déclaration d'un tenseur de 1 (2*3*4)
print(np.ones((2,3,4)))
print()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]



In [10]:
# Déclaration d'une matrice via fonction range
# Générée une liste de nombre dans l'intervalle [3.2, 4.8[ avec un pas de 0.2
print(np.arange(3.2, 4.8, 0.2))


[3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6]


### Initialisation avec une fonction utilisateur

In [15]:
# Définition d'une fonction que Numpy utilisera 
def function_for_numpy(x, y):
    return x+y

# Création d'un tableau en utilisant la fonction au dessus
# Elle doit contenir autant de paramètre qu'il n'y a de coordonnées
np.fromfunction(function_for_numpy, (3,3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Accèder aux items d'un tableau multidimensionnel

### Accès direct

In [ ]:
# Déclaration d'une matrice
A = np.array([[10,11,12],
              [20,21,22],
              [30,31,32],
              [40,41,42]])

print(A[3,2])

42


In [18]:
# Déclaration d'un tenseur
B = np.array([[[10,11,12],
              [20,21,22]],
             [[30,31,32],
              [40,41,42]]])

print(B[0,1,2])

22


### Accès via itération sur les éléments

In [20]:
C = np.array([[10,11,12],
              [20,21,22],
              [30,31,32],
              [40,41,42]])

# Itération sur une matrice "applatie"
for e in C.flat:
    print(e)

10
11
12
20
21
22
30
31
32
40
41
42


### Accès à une portion (slice) de matrice

In [27]:
D = np.array([[10,11,12],
              [20,21,22],
              [30,31,32],
              [40,41,42]])

print("Toutes les lignes, seulement la colonne d'index 2 :")
print(D[:,2])
print()

print("Seulement la ligne d'index 3, toutes les colonnes :")
print(D[3,:])
print()

print("Seulement les lignes d'index 1 à 2, seulement les colonnes d'index 1 et 2 :")
print(D[1:3,1:3])
print()

print("Seulement les deux dernières lignes, seulement la dernière colonne :")
print(D[-2:,-1])

Toutes les lignes, seulement la colonne d'index 2 :
[12 22 32 42]

Seulement la ligne d'index 3, toutes les colonnes :
[40 41 42]

Seulement les lignes d'index 1 à 2, seulement les colonnes d'index 1 et 2 :
[[21 22]
 [31 32]]

Seulement les deux dernières lignes, seulement la dernière colonne :
[32 42]


### Masques

In [29]:
# Déclaration d'une matrice via la un reshape du resultat de la fonction arrange de Numpy
A = np.arange(12).reshape(3,4)

print("Matrice A :")
print(A)
print()

b = A>4

print("Masque b :")
print(b)
print()

print("Matrice A avec le masque b :")
print(A[b])
print()

Matrice A :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Masque b :
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]

Matrice A avec le masque b :
[ 5  6  7  8  9 10 11]



## Manipuler les dimensions d'un tableau Numpy

### Connaitre les dimensions d'un tableau

In [31]:
# Déclaration d'une matrice C
C = np.array([[  0,  1,  2],
               [ 10, 12, 13],
               [100,101,102],
               [110,112,113]])

print("Dimensions de la matrice C :",C.shape)
print("Nombre de dimensions :", len(C.shape))
print()

# Déclaration d'un vecteur v
v = np.array([1,2,3,4])

print("Dimensions du vecteur v :",v.shape)
print("Nombre de dimensions :", len(v.shape))

Dimensions de la matrice C : (4, 3)
Nombre de dimensions : 2

Dimensions du vecteur v : (4,)
Nombre de dimensions : 1


### Modifier les dimensions d'un tableau

In [35]:
D = np.array([[  0,  1,  2],
               [ 10, 12, 13],
               [100,101,102],
               [110,112,113]])

print("Matrice D {} :".format(D.shape))
print(D)
print()

# Attention qu'il y ait le même nombre d'éléments !
E = D.reshape((2,6))

print("Matrice E {} :".format(E.shape))
print(E)
print()

# Utiliser -1 pour laisser Numpy calculer la dimension manquante en fonction de l'autre et du nombre d'éléments
F = E.reshape((-1, 4))

print("Matrice F {} :".format(F.shape))
print(F)
print()

Matrice D (4, 3) :
[[  0   1   2]
 [ 10  12  13]
 [100 101 102]
 [110 112 113]]

Matrice E (2, 6) :
[[  0   1   2  10  12  13]
 [100 101 102 110 112 113]]

Matrice F (3, 4) :
[[  0   1   2  10]
 [ 12  13 100 101]
 [102 110 112 113]]

