# Numpy : algèbre linéraire

In [16]:
import numpy as np

## Définition et notations

In [17]:
# Vecteur
V = np.array([1,2,3], dtype=int) # dtype optionnel, int par défaut
print(V)
print(V.shape)
print()

# Matrice
M = np.array([[1,2,3],
              [4,5,6]])
print(M)
print(M.shape)
print()

# Tenseur
T = np.array([[[1,2,3], [4,5,6]],
              [[7,8,9], [10,11,12]]])
print(T)
print(T.shape)
print()


[1 2 3]
(3,)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)



## Opérations avec vecteurs et matrices

### Vecteurs

In [18]:
# Définition vecteurs u et v
u = np.array([6,0,2])
v = np.array([-1,-2,3])

print("Vecteur u :")
print(u)
print()

print("Vecteur v :")
print(v)

Vecteur u :
[6 0 2]

Vecteur v :
[-1 -2  3]


In [ ]:
# Addition
print("u + v :")
print(u + v)
print()

# Soustraction
print("u - v :")
print(u - v)
print()

# Scaling
print("3u :")
print(3*u)

u + v :
[ 5 -2  5]

u - v :
[ 7  2 -1]

3u :
[18  0  6]


In [ ]:
# Norme d'un vecteur
print("||u|| :", np.linalg.norm(u))
print("||v|| :", np.linalg.norm(v))
print()

# Produit de vecteurs (dot product)
print("u.v :")
print(u.dot(v))

||u|| : 6.324555320336759
||v|| : 3.7416573867739413

Dot product u.v :
0


### Matrices

In [21]:
# Définitions des matrices
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[10,10,10],
              [20,20,20],
              [30,30,30]])

print("Matrice A :")
print(A)
print()

print("Matrice B :")
print(B)

Matrice A :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrice B :
[[10 10 10]
 [20 20 20]
 [30 30 30]]


In [22]:
# Addition
print("A + B :")
print(A+B)
print()

# Soustraction
print("A - B :")
print(A-B)
print()

# Scaling
print("2A :")
print(2*A)

A + B :
[[11 12 13]
 [24 25 26]
 [37 38 39]]

A - B :
[[ -9  -8  -7]
 [-16 -15 -14]
 [-23 -22 -21]]

2A :
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
# Produits de matrices

print("Produit avec l'opérateur @")
print("Produit de matrice A@B :")
print(A@B)
print()
print("Produit de matrice B@A :")
print(B@A)
print()

print("Produit avec Dot product")
print("Produit de matrice A.B :")
print(A.dot(B))
print()
print("Produit de matrice B.A :")
print(B.dot(A))
print()


Produit avec l'opérateur @
Produit de matrice AB :
[[140 140 140]
 [320 320 320]
 [500 500 500]]

Produit de matrice BA :
[[120 150 180]
 [240 300 360]
 [360 450 540]]

Produit avec Dot product
Produit de matrice A.B :
[[140 140 140]
 [320 320 320]
 [500 500 500]]

Produit de matrice B.A :
[[120 150 180]
 [240 300 360]
 [360 450 540]]



### Matrice-Vecteur

In [ ]:
# Définition d'une matrice
C = np.array([[1,2],
              [3,4],
              [5,6]])

# Définition d'un vecteur
x = np.array([5, -2])

print(" Matrice C {} :".format(C.shape))
print(C)
print()

print("Vecteur x {} :".format(x.shape))
print(x)
print()

y = C@x
print("Produit de C@x {} :".format(y.shape))
print(y)

 Matrice C (3, 2) :
[[1 2]
 [3 4]
 [5 6]]

Vecteur x (2,) :
[ 5 -2]

Produit de C @ x (3,) :
[ 1  7 13]


## Matrice transposée

In [27]:
# Transposée
print("Transposée de A :")
print(A.T)
print()

print("Transposée de B :")
print(B.T)
print()

print("Transposée de A.B :")
print((A@B).T)
print()

print("Transposée de B @ Transposée de A:")
print((B.T)@(A.T))
print()

Transposée de A :
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Transposée de B :
[[10 20 30]
 [10 20 30]
 [10 20 30]]

Transposée de A.B :
[[140 320 500]
 [140 320 500]
 [140 320 500]]

Transposée de B @ Transposée de A:
[[140 320 500]
 [140 320 500]
 [140 320 500]]



## Matrice identitée

In [29]:
# Définition d'une matrice identité
I = np.identity(3, dtype=int)

print("Matrice identité I :")
print(I)
print()

print("IA :")
print(I@A)
print()

print("AI :")
print(A@I)

Matrice identité I :
[[1 0 0]
 [0 1 0]
 [0 0 1]]

IA :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

AI :
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Matrice inversée

In [ ]:
# Définition d'une matrice
D = np.array([[3,0,2],
              [2,0,-2],
              [0,1,1]], dtype=int)

print("Matrice D :")
print(D)
print()

D_inv = np.linalg.inv(D)
print("Inverse de D :")
print(D_inv)
print()

print("Produit de la matrice et de son inverse :")
print("D@D_inv :")
print((D@D_inv).round(2))
print()
print("D_inv@D :")
print((D_inv@D).round(2))

Matrice D :
[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]

Inverse de D :
[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]

Produit de la matrice et de son ainverse :
D@D_inv :
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]

D_inv@D :
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Collinéarité et orthogonalité

In [35]:
# Définition de la matrice
U = np.array([[2/3, -2/3, 1/3],
              [1/3, 2/3, 2/3],
              [2/3, 1/3, -2/3]])

print("Matrice U:")
print(U)
print()

print("Transposée de U:")
print(U.T)
print()

print("Produit de la matrice transposée avec la matrice :")
print((U.T @ U).round(2)) 

Matrice U:
[[ 0.66666667 -0.66666667  0.33333333]
 [ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]

Transposée de U:
[[ 0.66666667  0.33333333  0.66666667]
 [-0.66666667  0.66666667  0.33333333]
 [ 0.33333333  0.66666667 -0.66666667]]

Produit de la matrice transposée avec la matrice :
[[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]


## Système d'equations linéraires : représentation en matrice

In [38]:
# 1*x1+2*x2=5
# 3*x1+9*x2=21
# Sous la forme A*x=b
# A une matrice
# x et b des vecteurs


A = np.array([[1,2],  # première équation
              [3,9]]) # seconde équation

print("Matrice A :")
print(A)
print()

b = np.array([5,21]) # résultats des deux équations

print("Vecteur b :")
print(b)
print()

# Ax=b
# => A-1*A*x = A-1*b
# => 1x = A-1*b
# => x = A-1*b

# Méthode 1 en détaillant le calcul avec la matrice inversée linalg.inv
A_inv = np.linalg.inv(A)

print("Inversion de matrice A :")
print(A_inv)
print()

x = A_inv@b
print("x = A-1 @ b :")
print(x)
print()

# Méthode 2 en utilisant linalg.solve
x = np.linalg.solve(A, b)
print("x :")
print(x)
print()


Matrice A :
[[1 2]
 [3 9]]

Vecteur b :
[ 5 21]

Inversion de matrice A :
[[ 3.         -0.66666667]
 [-1.          0.33333333]]

x = A-1 @ b :
[1. 2.]

x :
[1. 2.]



## Diagonalisation de matrices

In [43]:
# Déclaration de la matrice
A = np.array([[3,4,-2],
              [1,4,-1],
              [2,6,-1]])

print("Matrice A :")
print(A)
print()

eigenvals, eigenvecs = np.linalg.eig(A)

print("Valeurs propres (eigenvalues) de A :")
print(eigenvals)
print()

print("Vecteur propre (eigenvectors) de A :")
print(eigenvecs.round(3))
print()

print("Effet de A sur son premier vecteur propre :")
print(A@eigenvecs[:,0])
print()

print("Si on multiplie (scale) le premier vecteur propre, par sa valeur propre associée :")
print(eigenvals[0]*eigenvecs[:,0])
print()

Matrice A :
[[ 3  4 -2]
 [ 1  4 -1]
 [ 2  6 -1]]

Valeurs propres (eigenvalues) de A :
[3. 2. 1.]

Vecteur propre (eigenvectors) de A :
[[-0.408  0.     0.707]
 [-0.408  0.447 -0.   ]
 [-0.816  0.894  0.707]]

Effet de A sur son premier vecteur propre :
[-1.22474487 -1.22474487 -2.44948974]

Si on multiplie (scale) le premier vecteur propre, par sa valeur propre associée :
[-1.22474487 -1.22474487 -2.44948974]

