# Data manipulation with numpy

In [2]:
import numpy as np

## Dealing with vectors

In [10]:
# start : O
# end : 10.5 (exclude !)
# step : 0.5
vec = np.arange(0, 10.5, 0.5)

print("Vector vec : ",vec)
print("Shape of vec: ",vec.shape)
print("7th element of vec :", vec[6])
print("3 first items of vec :", vec[:3])
print("3 last items of vec :", vec[-3:])
# mask = vec < 7
# print("Values of vec below 7, using mask :", vec[mask])
print("Values of vec below 7, using mask :", vec[vec<7])

Vector vec :  [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
Shape of vec:  (21,)
7th element of vec : 3.0
3 first items of vec : [0.  0.5 1. ]
3 last items of vec : [ 9.   9.5 10. ]
Values of vec below 7, using mask : [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5]


## Dealing with matrices

In [ ]:
def my_func(x,y):
    return x**2+y

mat = np.fromfunction(my_func, (4,4), dtype=int)

print("Matrix mat (create by function) :")
print(mat)
print()

for e in mat.flat:
    print("When dividing {} by 2, the remainder is : {}".format(e, e%2))

Matrice mat (create by function) :
[[ 0  1  2  3]
 [ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 12]]

When dividing 0 by 2, the remainder is : 0
When dividing 1 by 2, the remainder is : 1
When dividing 2 by 2, the remainder is : 0
When dividing 3 by 2, the remainder is : 1
When dividing 1 by 2, the remainder is : 1
When dividing 2 by 2, the remainder is : 0
When dividing 3 by 2, the remainder is : 1
When dividing 4 by 2, the remainder is : 0
When dividing 4 by 2, the remainder is : 0
When dividing 5 by 2, the remainder is : 1
When dividing 6 by 2, the remainder is : 0
When dividing 7 by 2, the remainder is : 1
When dividing 9 by 2, the remainder is : 1
When dividing 10 by 2, the remainder is : 0
When dividing 11 by 2, the remainder is : 1
When dividing 12 by 2, the remainder is : 0


In [15]:
# mask = mat%2==0
even_numbers = mat[mat%2==0]

print("Even numbers matrix :")
print(even_numbers)
print()

even_numbers = np.reshape(even_numbers, (2,4))
print("Even numbers matrix after reshape {} :", even_numbers.shape)
print(even_numbers)
print()

print("Even numbers matrix, log applied :")
print(np.log(even_numbers))

Even numbers matrix :
[ 0  2  2  4  4  6 10 12]

Even numbers matrix after reshape {} : (2, 4)
[[ 0  2  2  4]
 [ 4  6 10 12]]

Even numbers matrix, log applied :
[[      -inf 0.69314718 0.69314718 1.38629436]
 [1.38629436 1.79175947 2.30258509 2.48490665]]


/var/folders/yt/qrbwlc0x6fj2rs4chrxkrm_m0000gn/T/ipykernel_20412/459335352.py:14: RuntimeWarning: divide by zero encountered in log
  print(np.log(even_numbers))


## From vector to matrix, from matrix to tensor and the way back

In [20]:
vector = np.arange(100)

print("Vector :")
print(vector)
print()

matrix = np.reshape(vector, (10,10))

print("Matrix :")
print(matrix)
print()

tensor = np.reshape(matrix, (-1, 5, 5))

print("Tensor :")
print(tensor)
print()

Vector :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Matrix :
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

Tensor :
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85

In [26]:
print("Tensor first matrix :")
print(tensor[0,:,:])
print()

print("Tensor elements, first matrix, line index 1, colmun index 2 :")
print(tensor[0,1,2])
print()

print("Tensor elements, first matrix, colmun index 2 :")
print(tensor[0,:,2])
print()

print("Tensor elements, first matrix, line index 1 :")
print(tensor[0,1,:])
print()

Tensor first matrix :
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Tensor elements, first matrix, line index 1, colmun index 2 :
7

Tensor elements, first matrix, colmun index 2 :
[ 2  7 12 17 22]

Tensor elements, first matrix, line index 1 :
[5 6 7 8 9]



In [31]:
matrix_back = np.reshape(tensor, (10,10))

print("Matrix back :")
print(matrix_back)
print()

vector_back = np.reshape(matrix_back, (1,-1))

print("Vector back :")
print(vector_back)

Matrix back :
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

Vector back :
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
  72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
  96 97 98 99]]


## A famous theorem

In [ ]:
import plotly.express as px

uniform_values = np.random.uniform(0, 10, 10000)

px.histogram(uniform_values)

In [35]:
mean_values = []

for i in range(1000):
    mean_values.append(np.ndarray.mean(np.random.uniform(0, 10, 10000)))

px.histogram(mean_values)

It's a normale distribution => Central limit theorem