# Linear Algebra with Numpy

In [1]:
import numpy as np

## Operations with vectors and matrices

### Vector operations

In [2]:
u = np.array([2,9,-1])
v = np.array([1,5,3])

print("u+v :")
print(u+v)

u+v :
[ 3 14  2]


In [4]:
u = np.array([10,-2,1])
v = np.array([4,3,2])

print("u-v :")
print(u-v)

u-v :
[ 6 -5 -1]


In [6]:
u = np.array([1,-2,2])
v = np.array([2,1,0])

print("4*(u+v) :")
print(4*(u+v))

4*(u+v) :
[12 -4  8]


In [8]:
u = np.array([1,2,3,4])
v = np.array([-1,2,-3,4])

print("||u|| :", np.linalg.norm(u))
print("||v|| :", np.linalg.norm(v))

||u|| : 5.477225575051661
||v|| : 5.477225575051661


### Matrix operations

In [9]:
A = np.array([[1,2,3],
              [2,1,4],
              [3,4,1]])
B = np.array([[2,3,4],
              [3,2,5],
              [4,5,2]])

print("A+B :")
print(A+B)

A+B :
[[3 5 7]
 [5 3 9]
 [7 9 3]]


In [12]:
A = np.array([[1,2,3],
              [2,1,4],
              [3,4,1]])
B = np.array([[2,3,4],
              [3,2,5],
              [4,5,2]])

print("2*A-B :")
print(2*A-B)

2*A-B :
[[0 1 2]
 [1 0 3]
 [2 3 0]]


In [14]:
A = np.array([[1,0,2],
              [2,1,0],
              [1,2,1]])
B = np.array([[2,0,0],
              [1,2,0],
              [0,1,2]])

print("AB :")
print(A@B)
print()

print("BA :")
print(B@A)

AB :
[[2 2 4]
 [5 2 0]
 [4 5 2]]

BA :
[[2 0 4]
 [5 2 2]
 [4 5 2]]


In [15]:
A = np.array([[1,0],
              [2,1],
              [1,2]])
B = np.array([[2,0,0],
              [1,2,0]])

print("AB :")
print(A@B)
print()

print("BA :")
print(B@A)

AB :
[[2 0 0]
 [5 2 0]
 [4 4 0]]

BA :
[[2 0]
 [5 2]]


### Matrix-vector product

In [16]:
A = np.array([[1,0,2],
              [2,1,0],
              [1,2,1]])
v = np.array([-1, 1, 2])

print("Av :")
print(A@v)

Av :
[ 3 -1  3]


## Collinearity and orthogonality

In [ ]:
u = np.array([2,-3,-1])
v = np.array([3,1,3])

print("u.v :")
# print(u.dot(v))
print(np.dot(u, v))

u.v :
0


It means that they're orthogonal => u.v = ||u|| * ||v|| * cos(90°) = 0

In [ ]:
u = np.array([4,2,-1])
v = np.array([-1,-0.5,0.25])

print("u/v :")
print(u/v)


u/v :
[-4. -4. -4.]


Those vectors are collinear => u = -4*v

In [19]:
u = np.array([1,2])
v = np.array([-2,1])
w = np.array([-1,3])

print("u : ")
print(u)
print()
print("w-v :")
print(w-v)

u : 
[1 2]

w-v :
[1 2]


Those vectors are multicollinear => w = a\*u+b\*v

## Systems of linear equations

In [24]:


A = np.array([[2,1,0],
              [1,2,1],
              [0,1,2]])

c = np.array([2,0,1])

# First method
# Knowing the following :
# A*x=c
# A-1*A*x=A-1*c
# 1x=A-1*c
# x=A-1*c

# A_inv = np.linalg.inv(A)
# x = A_inv@c

# Second method
# Using numpy linalg
print("x :")
print(np.linalg.solve(A, c))
print()


x :
[ 1.75 -1.5   1.25]



## Matrix diagonalization

In [26]:
A = np.array([[3, -1],
              [2, 0]])

u = np.array([1, 1])
v = np.array([1, 2])

print("Au :")
print(A@u)
print()

print("Av :")
print(A@v)
print()

Au :
[2 2]

Av :
[1 2]



A\*u = 2*u => u eigenvector of A with eigenvalue 2

A\*v = v => v eigenvector of A with eigenvalue 1

In [27]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues :")
print(eigenvalues)
print()

print("Eigenvectors :")
print(eigenvectors)
print()

Eigenvalues :
[2. 1.]

Eigenvectors :
[[0.70710678 0.4472136 ]
 [0.70710678 0.89442719]]

